async function loadCatalog(){try{catalog=await fetch('https://raw.githubusercontent.com/bennessism/window/main/weather/catalog.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()})}catch(e){catalog={default:{country:'my',location:'selangor'},countries:{my:{name:'Malaysia',locations:[{id:'selangor',name:'Selangor',city:'Shah Alam',lat:3.0738,lon:101.5183}]}}}}populateCountries()}
function populateCountries(){countrySelect.innerHTML='';Object.entries(catalog.countries).forEach(([id,c])=>{const o=document.createElement('option');o.value=id;o.textContent=c.name;countrySelect.append(o)});countrySelect.value=localStorage.getItem('windCountry')||catalog.default.country||'my';if(!catalog.countries[countrySelect.value])countrySelect.value=Object.keys(catalog.countries)[0];populateLocations()}
function populateLocations(){locationSelect.innerHTML='';const c=catalog.countries[countrySelect.value];c.locations.forEach(l=>{const o=document.createElement('option');o.value=l.id;o.textContent=l.name+(l.city&&l.city!==l.name?' · '+l.city:'');locationSelect.append(o)});const saved=localStorage.getItem('windLocation')||catalog.default.location;if(c.locations.some(l=>l.id===saved))locationSelect.value=saved}
function selectedLocation(){const c=catalog.countries[countrySelect.value];return c.locations.find(l=>l.id===locationSelect.value)||c.locations[0]}
function labelFor(loc){return loc.city&&loc.city!==loc.name?`${loc.name} · ${loc.city}`:loc.name}
function areaFor(loc){return loc.name||loc.city||'Location'}
function fmtTime(iso){if(!iso)return'--';const m=String(iso).match(/T(\d{2}):(\d{2})/);if(!m)return'--';let h=Number(m[1]);const min=m[2],s=h>=12?'PM':'AM';h=h%12||12;return`${h}:${min} ${s}`}
function refreshUI(updatedIso){const strength=windStrength(wind),dir=compassName(windDir);summaryLine.textContent=`${currentArea} · ${strength} · ${Math.round(wind)} km/h`;detailLoc.textContent=currentPlace;conditionEl.textContent=strength;speedEl.textContent=Math.round(wind);gustEl.textContent=Math.round(gust)+' km/h';fromText.textContent='From '+dir;directionEl.textContent=`${dir} · ${Math.round(windDir)}°`;updatedEl.textContent='Updated '+fmtTime(updatedIso)}
async function loadWind(lat=currentLat,lon=currentLon,label=currentPlace,area=currentArea){currentLat=lat;currentLon=lon;currentPlace=label;currentArea=area;try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m,is_day&wind_speed_unit=kmh&timezone=auto`;const j=await fetch(u,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()});wind=Number(j.current.wind_speed_10m)||0;gust=Number(j.current.wind_gusts_10m)||wind;windDir=Number(j.current.wind_direction_10m)||0;isDay=Number(j.current.is_day)===1;document.querySelector('meta[name="theme-color"]').content=isDay?'#76b7e8':'#07111f';refreshUI(j.current.time);seedScene(stage.clientWidth,stage.clientHeight)}catch(e){summaryLine.textContent=currentArea+' · data unavailable'}}
function useBrowserLocation(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>{picker.classList.remove('show');loadWind(p.coords.latitude,p.coords.longitude,'Your location','Your location')},()=>{},{enableHighAccuracy:false,timeout:8000,maximumAge:600000})}
summaryBtn.onclick=()=>{const open=detailCard.classList.toggle('show');summaryBtn.classList.toggle('open',open);if(!open)picker.classList.remove('show')};
document.getElementById('detailClose').onclick=()=>{detailCard.classList.remove('show');summaryBtn.classList.remove('open');picker.classList.remove('show')};
document.getElementById('changeLocationBtn').onclick=()=>picker.classList.toggle('show');countrySelect.onchange=populateLocations;document.getElementById('myLocationBtn').onclick=useBrowserLocation;document.getElementById('applyLocationBtn').onclick=()=>{const loc=selectedLocation();localStorage.setItem('windCountry',countrySelect.value);localStorage.setItem('windLocation',loc.id);picker.classList.remove('show');loadWind(loc.lat,loc.lon,labelFor(loc),areaFor(loc))};
scroller.addEventListener('scroll',()=>{if(innerWidth>700)return;const i=Math.max(0,Math.min(2,Math.round(scroller.scrollLeft/innerWidth)));document.querySelectorAll('.dots i').forEach((d,n)=>d.classList.toggle('on',n===i))},{passive:true});addEventListener('resize',resize);resize();requestAnimationFrame(draw);loadCatalog().then(()=>{const loc=selectedLocation();loadWind(loc.lat,loc.lon,labelFor(loc),areaFor(loc))});setInterval(()=>loadWind(),10*60*1000);